Version 1.03. Uses 'getopts'. Adds a new argument '-s' for passing a separator. Some changes might require to allow passing tab characer as a separator.

diff --git a/metaviewer b/metaviewer
--- a/metaviewer
+++ b/metaviewer
@@ -1,7 +1,8 @@
 #!/bin/sh
+set -euo pipefail
 
 #version of the script
-_VER_NUM=1.02
+_VER_NUM=1.03
 _VERSION="`basename ${0}` (version: $_VER_NUM)" 
 
 #define main variables
@@ -10,85 +11,56 @@ _U="mt_internal_user" #"mt_internal_user"	#sql server user
 _P="se@lf0n1nt3rn@l" #"se@lf0n1nt3rn@l"	#password
 _D=dw_motrpac			#database name
 
-EXPECTED_ARGS="-r -i -f -h -v -d"
 _HELP="\n$_VERSION
 	\nPrerequisites: 'sqlcmd' application is required to run this script. To install 'sqlcmd', follow directions on this site: \nhttps://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017
 	\n\narguments usage: 
-		\n\t[-v: report the version]
-		\n\t[-h: help]
+		\n\t[-v: report the version; if this argument is supplied, it aborts execution of the script]
+		\n\t[-h: help; if this argument is supplied, it aborts execution of the script]
 		\n\t[-d: debug version]
-		\n\t[-r report identifier (optional) - expected values: metadata|dictionary|studystats (default: studystats)] 
-		\n\t[-i study or dictionary id (optional): numeric (default: 1) 
-		\n\t\tthis argument is required for 'metadata' and 'dictionary' reports (refer to '-r' argument); 'studystats' does not require this argument]
-		\n\t[-f format (optional): sets delimiter for the output (default value is comma); accepts one character only
-		\n\t\tIf this argument is omitted, native SQL Server output will be used]"
+		\n\t[-r report identifier: expected values: metadata|dictionary|studystats (if '-r' is omitter, default report value is set to 'studystats')] 
+		\n\t[-i id of entity (study or dictionary id) to be supplied to selected report: numeric or comma delimited list of numeric values (if '-i' is omitter, default id value is set to 1) 
+		\n\t\tthis argument is required for 'metadata' and 'dictionary' reports (refer to '-r' argument); 
+		\n\t\t'studystats' does not require this argument
+		\n\t\t'metadata' report can accept a comma delimited list of study_ids; 
+		\n\t\t'dictionary' report can accept only single value]
+		\n\t[-f format (optional): sets output format to be delimited. Actual delimiter to be used will be defined by '-fd' paramter (if '-fd' is omitted, default delimiter is set to comma)
+		\n\t\tIf this argument is omitted, native SQL Server output will be used]
+		\n\t[-s separator: sets delimiter character to be used when '-f' argument is provided. If this argument is omitted, default delimiter is set to comma); 
+		\n\t\taccepts one character only]
+		"
 
-_NEXT="" #variable to handle name of the next variable being assigned
+#set default values
 _PR="studystats"	#default value for query name
 _PI="1"				#default value for id
-_PF="" 				#default value for a delimiter; if "-f" argument is provided, comma "," will be set as default
-
-#echo $2
-
-
-#echo $*
-#for PRM in $*
-#do
-#	echo $PRM
-#done
-#echo $#
-#for PRM in $@
-#do
-#	echo "${PRM}" #$PRM
-#done
-
+_PF="" 				#default value for a format argument; 
+_PS=","				#default separator for a delimited format;
 
 #analyze received arguments
-for PRM in $@
+while getopts r:i:fhvds: o
 do
-  #check if the provided named argument is expected
-  if [ ${PRM:0:1} == "-" ] #check if this is the named argument
-  then #echo "named argument $PRM"; fi
-	  if [[ ! " $EXPECTED_ARGS " =~ .*\ $PRM\ .* ]]
-	  then
-		echo "Incorrect argument '$PRM' was supplied. Check below for the help information."
-		echo -e $_HELP
-		exit 0
-	  fi
-  fi
-  
-  case "$PRM" in
-    -r) _NEXT="_PR";;
-    -i) _NEXT="_PI";;
-    -f) _NEXT="_PF"
-		_PF="," #default value; if "-f" argument is provided, the default value is set to make sure that it is in place even if user did not specify the desired delimiter
-    ;;
-	-d) _PD="1";;
-	-h) 
-		echo -e $_HELP
-		exit 0
-	;;
-	-v) 
-		echo -e $_VERSION
-		exit 0
-	;;
-    *)
-		#echo "_NEXT=" $_NEXT
-		case "$_NEXT" in
-		   _PR) _PR="$PRM"; _NEXT="";;
-		   _PI) _PI="$PRM"; _NEXT="";;
-		   _PF) _PF="$PRM"; _NEXT="";;
-		   *) _NEXT="";; #reset variable
-		esac 
-    ;;
-  esac
+    case "$o" in
+	r) _PR="$OPTARG";;
+	i) _PI="$OPTARG";;
+	f) _PF="1";;
+	s) _PS="$OPTARG";;
+	d) _PD="1";;
+	v) echo -e $_VERSION
+	   exit 0;;
+	h) echo -e $_HELP
+	   exit 0;;
+	*) echo "$0: invalid option -$o" >&2
+	   echo -e $_HELP
+	   exit 1;;
+    esac
 done
+shift $((OPTIND-1))
 
 #output values of arguments in debug mode
-if [ "$_PD" == "1" ]; then
+if [ "$_PD" == "1" ]; then #output in debug mode only
     echo "Report (-r): " $_PR
     echo "Id (-i): " $_PI
-    echo "Format/Delimiter (-f):" $_PF
+    echo "Format (-f):" $_PF
+    echo "Separator (-s):" [$_PS]
 fi
 
 #possible SQL scripts (metadata|dictionary|studystats)
@@ -103,7 +75,7 @@ _PL_HLDR_STUDYID="{{study_id}}"
 #controls format of the output
 if [ "$_PF" != "" ]
 then
-  _DELIM_FMT="-W -w 4000 -s $_PF"
+  _DELIM_FMT="-W -w 4000 -s $_PS"
   _RMV_2ND_LINE=" | sed '2d'"
 else
   _DELIM_FMT=""
@@ -114,13 +86,13 @@ fi
 
 
 case $_PR in
-   metadata) #_QR=$_Q_METADATA
+   metadata) 
 		#check if PI contains multiple comma separated IDs 
 		IFS=',' read -ra IDS <<< "$_PI"
 		if [ "${#IDS[@]}" -gt 1 ]
-		then
-			_QR=$_Q_METADATA_MULTI_IDS
-		else
+		then #multiple IDs are present
+			_QR=$_Q_METADATA_MULTI_IDS 
+		else #only one ID is present
 			_QR=$_Q_METADATA
 		fi
    
@@ -135,13 +107,13 @@ case $_PR in
 	 ;;
 esac 
 
-#update _QR variable by substituting study_id place holder with the actual study_id supplied as a argument
+#update _QR variable by substituting study_id place-holder with the actual study_id supplied as an argument
 _QR=${_QR//$_PL_HLDR_STUDYID/$_PI}
 
 if [ "$_PD" == "1" ]; then
-	echo "_QR = " $_QR #for testing only
+	echo "SQL Query: " $_QR #output in debug mode only
 fi
-#exit 0 #for testing only
+
 
 _SQLCMD='sqlcmd -S $_S -U $_U -P $_P -d $_D -Q "$_QR" $_DELIM_FMT'  # -W -w 4000 -s , 
 #echo $_SQLCMD #for testing only
